version: '3'
services:
  nginx:
    container_name: nginxcontainer
    image: nginx
    ports:
      - '8000:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro


  authservice:
    # container_name: authcontainer
    build:
      context: ./Auth Service
    image: authserviceimage:v1
    ports:
      - '9000:9000'
    env_file:
      - ./Auth Service/.env